### ISSUE TITLE
Audience

### ISSUE THREAD

**Issue by adhisun** [salesforceidentity/ws-federation#1]
Hello

Our partner is using WSFederation and needs the Audience which I believe is not currently available in the setup as a configurable property.

In the APEX code, 'AUDIENCE' is mapped to realm.realm__c, where realm.realm__c = "urn:sharepoint:salesforce". 

But the Service provider is expecting the AUDIENCE in the site name / URL format "https://....."

As of now , I have hard coded the value for testing. 

Can you help to update this package to include the AUDIENCE as a new field/attribute.

We are the new customer of Salesforce Identity.

**Comment by cmortimore** [comment]
Resolved in latest push
